### ISSUE TITLE
Missing service name in API endpoint

### ISSUE THREAD

**Issue by andersfylling** [DM848/dashboard#6]
https://github.com/DM848/dashboard/blob/221eba21e0c68dc4d953a55996ba8fa5df29d210/src/store/services/actions.js#L20

This doesn't target any active service. The pattern is `/api/<service-name>/` for targeting a service. And won't create a new service.

To deploy a new service using the service-generator you use the following
Method: POST
URL: `/api/service-generator/service`

See more about the service-generator here: [service-generator](https://github.com/DM848/srv-service-generator)

See more about how the ACL gateway works: [acl](https://github.com/DM848/srv-acl)

Note that the currently active branch in ACL repo is `feature/enforcer` when writing this (if it's gone, then that branch has been merged into master and is now deleted).

**Comment by kmailla** [comment]
changed it to this url
